version: "3"
services:
  frontend:
    container_name: PG50477-Stepwise-Source-Frontend
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "50740:80"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  backend:
    container_name: PG50477-Stepwise-Source-Backend
    build:
      context: ./backend
    ports:
      - "50741:50741"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: PG50477-Stepwise-Source-Mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "50744:27017"

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridges
