version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: PG50477-Stepwise-Source-Mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "50744:27017"

  backend:
    container_name: PG50477-Stepwise-Source-Backend
    build:
      context: ./backend
    depends_on:
      - mongo
    ports:
      - "50741:50741"
    volumes:
      - ./backend:/app
    env_file:
      - ../.env.production # Load the production env file
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017/

  frontend:
    container_name: PG50477-Stepwise-Source-Frontend
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "50740:80"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridges
